PureBhaktiArchive/audioseva

functions/src/helpers.ts, functions/src/index.ts, functions/src/modules/SQR.functions.ts, functions/src/modules/reporting.sync.functions.ts
Adapted the code to the new data structure.
=> Monitor storage and add file entries into Database - new Data structure

README.md, functions/package.json, functions/src/helpers.ts, functions/src/modules/SQR.functions.ts
The spreadsheet url is hardcoded cause I didn't where it should come from .. will it be an environment variable or should it be read from a path at the database.
=> Transfer SQR data from the spreadsheet into Database

README.md, db.rules, functions/package.json, functions/src/index.ts, functions/src/modules/SE.functions.ts
1. Ensure sound editor's `uploadCode`
2. Update the task
3. Notify the assignee
=> SE: Allotment Processing

functions/.prettierrc, functions/package-lock.json, functions/package.json, functions/src/helpers.ts, functions/src/index.ts, functions/src/modules/Authorization.functions.ts, functions/src/modules/SE.functions.ts, functions/src/modules/SQR.functions.ts, functions/src/modules/email.functions.ts, functions/src/modules/reporting.sync.functions.ts
Enforce same styles throughout `/functions` codebase.
Make sure you have the VS Code Prettier extension installed if using VS Code
=> Prettier configuration for functions

functions/src/helpers.ts, functions/src/modules/SQR.functions.ts
https://trello.com/c/n2Jo3mOc/84-split-sqr-submissions-processing-function-into-two
=> Split SQR submissions processing function into two

functions/package-lock.json, functions/package.json, functions/src/helpers.ts, functions/src/modules/SQR.functions.ts
Merged function updateFilesOnNewAllotment() and sendEmailOnNewAllotment()
Moved helper function groupByMulti() to helpers.ts
Added return type to helper groupByMulti() function
Installed moment-js for formatting date
=> Merge SQR allotment processing functions into one

README.md
Added information about transpiling command in README
=> Update README for building and deploying functions

functions/src/modules/SQR.functions.ts, functions/src/services/GoogleSheets.ts
Fixed linting errors from SQR.functions.ts and GoogleSheets.ts
=> Fix linting errors in functions

database.rules.json, functions/src/modules/Users.functions.ts
Fixed errors: Promises must be handled appropriately from GoogleSheets.ts and SQR.functions.ts
=> Process registration webform data

email/registration.html, functions/src/modules/Users.functions.ts
Added registration.html file
Updated Users.functions.ts with registrationEmail()
=> Registration Email

functions/package.json, functions/src/modules/SQR.functions.ts, functions/src/services/GoogleSheets.ts
Changes to the `GoogleSheets` service created by **Adrien** still needs refinement ... This is just an initial draft.
=> Rewrite importing SQR spreadsheet

README.md, functions/src/index.ts, functions/src/modules/CR.functions.ts, functions/src/modules/SQR.functions.ts, functions/src/modules/User.functions.ts, functions/src/services/GoogleSheets.ts, functions/src/services/Sheet.ts
There's something that hasn't been considered .. Normally I check if `Submission serial` exists on the **target** sheet .. if so I do **not** copy the row from the **source** sheet (taking into consideration that it should be copied if `Fused Lectures` is set to **No**).
Now, what if 2 submission in the **source** sheet had the same `Submission serial` .. should I take that too into consideration?
This is **not** done automatically since importing is performed in batches, not row by row.
=> Copy new CR submissions into the processing spreadsheet

frontend/src/views/TE/Task.vue
https://trello.com/c/BjcRS4i7/182-te-task-page
=> Fix non coordinators viewing resolution controls

frontend/src/components/TE/TaskDefinition.vue
https://trello.com/c/uUmMF69m/186-te-support-sound-engineered-restored-source-files
=> TE: support Sound Engineered (restored) source files

frontend/src/views/Listen.vue
https://trello.com/c/UJZ6SPPY/83-listening-page
=> Listening page

frontend/src/components/TE/Resolution.vue
https://trello.com/c/2Ud97j87/145-te-tasks-list
=> TE Tasks List

frontend/src/views/Layout/MainLayout.vue
https://trello.com/c/kKEbVX9a/211-highlight-icon-only-for-the-current-section-in-the-menu
=> Highlight icon only for the current section in the menu

frontend/src/views/TE/Tasks.vue
https://trello.com/c/CGVykTpH/215-colored-progress-row-in-te-tasks-pagination
=> Colored progress row in TE Tasks pagination

database.rules.bolt, frontend/src/views/SQR/Form.vue, functions/src/schema/migrations/2019-10-16-sqr-migrated-submissions.ts
https://trello.com/c/R2MOhpbk/226-take-sqr-submissions-from-final-branch-as-a-fallback
=> Take SQR submissions from final branch as a fallback

frontend/src/validation.ts
https://trello.com/c/Ez9nOEPR/222-zero-padded-hour-should-be-accepted-in-timing
=> Zero-padded hour should be accepted in timing

frontend/src/components/SQRForm/SoundIssues.vue, frontend/src/components/SQRForm/SoundIssuesMixin.ts, frontend/src/components/SQRForm/UnwantedParts.vue, frontend/src/views/SQR/Form.vue
https://trello.com/c/bJfOtcc8/227-deleting-soundissue-besides-the-latest-soundissue-in-sqr-form-does-not-update-the-ui
=> Deleting soundIssue besides the latest soundIssue in SQR form does not update the ui

frontend/package-lock.json, frontend/src/views/SQR/Form.vue
https://trello.com/c/ATc2Diqp/229-sqr-submission-form-validation-message
=> SQR Submission Form validation message

frontend/src/views/SQR/Form.vue
https://trello.com/c/QBjmhWv9/239-no-created-property-in-submitted-form
=> No `created` property in submitted form

README.md, functions/src/SoundQualityReporting/SQRWorkflow.ts, functions/src/TrackEditing/Workflow.ts, functions/src/modules/Donations.functions.ts, functions/src/modules/Email.functions.ts
https://trello.com/c/vBwVFQGj/233-another-coordinator-for-te
https://trello.com/c/jM97KqLX/242-use-single-te-spreadsheet
=> TE Adjustments

frontend/src/views/Listen.vue
https://trello.com/c/ihb41kzM/245-listening-page-is-hanging-on-ios
=> Listening page is hanging on iOS

frontend/src/router.ts, frontend/tests/unit/router.spec.ts
https://trello.com/c/nZLVEbrC/241-navigation-redirects-to-wrong-route-after-login
=> Navigation redirects to wrong route after login

frontend/package-lock.json, frontend/src/store/modules/user.ts, frontend/src/views/SQR/Form.vue
https://trello.com/c/lLI19ZXG/232-dont-open-the-sqr-submission-form-if-the-token-is-invalid
=> Don't open the SQR submission form if the token is invalid

frontend/src/views/Listen.vue
https://trello.com/c/lKk3dKMN/240-the-audio-player-error-message-is-misleading
=> The audio player error message is misleading

frontend/package.json, frontend/src/main.ts, frontend/src/views/Layout/BaseLayout.vue
https://trello.com/c/Zf1blj0w/246-app-is-not-loading-on-ios-8-9
=> App is not loading on iOS 8, 9

database.rules.bolt, functions/src/modules/User.functions.ts
https://trello.com/c/N8qD09n9/252-customuserclaims-argument-must-be-an-object-or-null
=> Save user to the database only on creation.

frontend/package-lock.json, frontend/package.json, frontend/src/main.ts, frontend/src/shims-vue-page-title-aug.d.ts, frontend/src/types/vue-page-title/index.d.ts, frontend/src/views/CRAllotment.vue, frontend/src/views/DonationReceiptForm.vue, frontend/src/views/Home.vue, frontend/src/views/Listen.vue, frontend/src/views/Login.vue, frontend/src/views/SQR/Form.vue, frontend/src/views/SQRAllotment.vue, frontend/src/views/TE/Allotment.vue, frontend/src/views/TE/MyTasks.vue, frontend/src/views/TE/Task.vue, frontend/src/views/TE/Tasks.vue, frontend/src/views/TE/Upload.vue
https://trello.com/c/BfR0qG7s/248-manage-page-title
=> Manage page title

frontend/src/views/TE/Allotment.vue
https://trello.com/c/OUo9Ofpl/253-dont-save-all-user-details-into-te-assignee
=> Don't save all user details into TE assignee

.github/deploy.yml, .github/workflows/deployment.yml
https://trello.com/c/FF4HoIWx/68-continuous-integration-and-deployment
=> Implement deployment using Deliverybot.

.github/workflows/ci.yml
https://trello.com/c/FF4HoIWx/68-continuous-integration-and-deployment
=> CI on master

frontend/src/components/TE/TaskMixin.ts, frontend/src/views/TE/Task.vue
https://trello.com/c/7zvWPEnU/204-te-cancellation
=> TE Cancellation

firebase.json, frontend/.storybook/stories/TE.stories.js, frontend/src/components/TE/Output.vue, frontend/src/components/TE/VersionDownloadLink.vue, frontend/src/views/TE/Task.vue, functions/src/TrackEditing/TE.functions.ts
https://trello.com/c/bVlBUaCu/257-link-uploaded-te-files-to-the-firebase-storage
=> TE uploaded files should be downloadable

frontend/src/components/SQRForm/SoundIssuesMixin.ts
https://trello.com/c/xZrwdrwD/264-when-i-reopen-the-submitted-form-by-default-1-blank-unwanted-part-and-1-blank-sound-issue-is-getting-added
=> When i reopen the submitted form. By default 1 blank unwanted part and 1 blank sound issue is getting added.

functions/src/SoundQualityReporting/SQR.functions.ts, functions/src/SoundQualityReporting/SQRWorkflow.ts, functions/src/SoundQualityReporting/TasksRepository.ts
https://trello.com/c/gQy2hDZf/255-allow-coordinator-to-spare-files-in-the-sqr-allotments-sheet
=> Allow coordinator to spare files in the SQR Allotments sheet

frontend/src/components/TE/BaseTaskMixin.ts, frontend/src/components/TE/LastVersionMixin.ts, frontend/src/components/TE/Output.vue, frontend/src/components/TE/TaskMixin.ts, frontend/src/views/TE/Task.vue
https://trello.com/c/2Ud97j87/145-te-tasks-list
=> Fix task background color is wrong color for WIP status

functions/src/TrackEditing/Workflow.ts
https://trello.com/c/3PcPqPQJ/275-te-tasks-import-failure
=> Fix TE tasks import authentication problem

functions/src/Allotment.ts
https://trello.com/c/DxdWkrvn/276-date-parsing-error-in-te-import
=> Fix date parsing error in TE import

functions/src/TrackEditing/Workflow.ts
https://trello.com/c/Wt4ssRn3/307-te-cancellation-error-when-task-is-not-found-in-the-database
https://trello.com/c/iPBrcMW3/278-te-upload-error-when-task-is-not-found-in-the-database
=> Fix cancellation and upload errors for non-existing task

functions/src/Frontend.ts, functions/src/TrackEditing/TasksRepository.ts, functions/src/TrackEditing/TrackEditingTask.ts, functions/src/TrackEditing/Workflow.ts
https://trello.com/c/gMryyyEd/281-save-additional-columns-to-the-te-allotments-sheet
=> Save additional columns to the TE Allotments sheet

frontend/src/views/TE/Upload.vue
https://trello.com/c/EONmEN74/266-te-task-output-file-should-be-prompted-to-save-not-opened-in-the-browser
=> TE task output file should be prompted to save, not opened in the browser

frontend/src/views/TE/Upload.vue
https://trello.com/c/AYQCDbIE/279-upload-page-spacing-is-wierd
=> Fix: Upload page spacing is weird

frontend/src/views/TE/Upload.vue, functions/src/TrackEditing/TE.functions.ts
https://trello.com/c/EONmEN74/266-te-task-output-file-should-be-prompted-to-save-not-opened-in-the-browser
=> Fix Content-Disposition issue for TE output files

frontend/src/views/TE/Upload.vue
https://trello.com/c/AYQCDbIE/279-upload-page-spacing-is-wierd
=> Upload page spacing is wierd

frontend/src/views/SQR/Form.vue
https://trello.com/c/ZyVAJOjp/284-adapt-sqr-submission-form-for-mobile-browsers
=> Adapt SQR Submission Form for mobile browsers

frontend/src/components/TE/TaskDefinition.vue, frontend/src/views/TE/Task.vue
https://trello.com/c/WxtlhLPo/272-mention-the-operation-and-the-output-file-name-on-the-task-page
=> Mention the operation and the output file name on the task page

frontend/src/views/Listen.vue
https://trello.com/c/WuXLXpND/262-listening-page-improvements-in-ie11
=> Listening page improvements in IE11

frontend/src/router.ts, frontend/tests/unit/__snapshots__/HomePageButtons.spec.ts.snap, frontend/tests/unit/views/layout/__snapshots__/MainLayout.spec.ts.snap, functions/src/TrackEditing/TE.functions.ts
https://trello.com/c/U1u38ycU/309-ability-for-the-coordinator-to-upload-output-te-files-for-any-task
=> Ability for the TE coordinator to upload files for any task

frontend/src/views/TE/Task.vue
https://trello.com/c/IDkOo1Kg/286-show-error-message-if-te-task-is-not-accessible-to-the-user
=> Show error message if TE task is not accessible to the user

functions/src/Allotment.ts, functions/src/TrackEditing/TrackEditingTask.ts
https://trello.com/c/ogDG51KC/314-calculated-properties-in-database-cause-error
=> Fix: calculated properties in database cause an error.

functions/src/SoundEngineering/SE.functions.ts, functions/src/StorageManager.test.ts, functions/src/StorageManager.ts
https://trello.com/c/J28v53mR/243-arrange-restored-files-in-the-bucket-automatically
=> Arrange restored files in the bucket automatically

functions/src/Allotment.ts, functions/src/Spreadsheet.ts, functions/src/TrackEditing/TE.functions.ts, functions/src/TrackEditing/TasksRepository.ts
https://trello.com/c/h31SI51y/334-separate-tasks-import-and-allotments-syncing
=> Separate Tasks import and allotments syncing

frontend/src/views/TE/Task.vue
https://trello.com/c/Q4rkZvKD/318-show-warning-for-non-existent-task
=> Show warning for non-existent task

frontend/src/utility.ts, frontend/src/views/TE/Upload.vue, functions/src/StorageManager.test.ts, functions/src/StorageManager.ts, functions/src/TrackEditing/TE.functions.ts, storage.uploads.rules
https://trello.com/c/k1c1pZSH/341-require-mp3-files-for-digi-uploads
=> Require MP3 files for DIGI uploads

frontend/src/components/TE/TaskDefinition.vue
https://trello.com/c/GZBKtFGY/329-whitespace-in-the-beginning-of-the-unwanted-parts-in-te-task
=> Whitespace in the beginning of the unwanted parts in TE task

functions/src/Spreadsheet.ts, functions/src/TrackEditing/AllotmentRow.ts, functions/src/TrackEditing/ChunkRow.ts, functions/src/TrackEditing/TE.functions.ts, functions/src/TrackEditing/TaskValidator.ts, functions/src/TrackEditing/TasksRepository.ts, functions/src/TrackEditing/TrackEditingTask.ts
https://trello.com/c/t9jHhx5p/343-new-upload-causes-the-latest-resolution-columns-to-become-empty
=> New upload causes the Latest Resolution columns to become empty

functions/src/Spreadsheet.ts
https://trello.com/c/pAaA5PmM/273-incorrect-format-of-dates-in-te-allotments
=> Incorrect format of dates in TE Allotments

frontend/src/views/TE/Allotment.vue
https://trello.com/c/mxgj1jYz/317-simplify-tasks-listing-on-the-te-allotment-form
=> Simplify tasks listing on the TE allotment form

frontend/src/types/vue-confirmation-button/index.d.ts, frontend/src/views/TE/Task.vue
https://trello.com/c/nNP1L6xD/326-add-confirmation-for-te-approval-disapproval
=> Add confirmation for TE approval/disapproval

frontend/src/components/AssigneeSelector.vue, frontend/src/views/TE/Allotment.vue
https://trello.com/c/05kUAROZ/342-display-wip-given-stats-on-the-allotment-form-once-assignee-is-chosen
=> Display WIP/Given stats on the allotment form once assignee is chosen

frontend/src/main.ts, frontend/src/styles/main.css, frontend/src/views/SQRAllotment.vue, frontend/src/views/TE/Allotment.vue
https://trello.com/c/MlQRyyyq/338-add-ability-to-select-task-id-text-on-the-allotment-form
=> Add ability to select Task ID text on the allotment form

frontend/src/views/TE/Upload.vue
https://trello.com/c/8e43n642/320-te-upload-optimization
=> TE upload optimization

frontend/src/views/TE/MyTasks.vue
https://trello.com/c/GeRKi7fO/346-only-active-tasks-to-show-on-my-tasks-page
=> Show only active tasks on My Tasks page

frontend/.storybook/stories/TE.stories.js, frontend/src/components/TE/Output.vue, frontend/src/components/TE/Resolution.vue
https://trello.com/c/RM07ok8F/330-uniform-resolution-column-in-the-tasks-table
=> Uniform resolution column in the tasks table

functions/src/StorageManager.test.ts, functions/src/StorageManager.ts
https://trello.com/c/Wca79aZc/349-support-downloading-hi-files-without-a-b
=> Support downloading HI-files without A/B

.github/workflows/ci.yml, CRP/monitoring.ts, CRP/package-lock.json, CRP/package.json
https://trello.com/c/sZBWVpR7/354-move-crp-changelog-into-te-spreadsheet
=> Move CRP Changelog into TE spreadsheet

functions/src/Spreadsheet.ts
https://trello.com/c/RwYxx6K6/277-spreadsheet-error-if-no-frozen-rows
=> Spreadsheet error if no frozen rows

frontend/.storybook/stories/TE.stories.js, frontend/src/components/TE/RestoredChip.vue, frontend/src/components/TE/TaskDefinition.vue, frontend/src/views/TE/Allotment.vue
https://trello.com/c/tcf8xk0d/295-indicate-that-the-te-task-is-based-on-the-restored-files
=> Indicate that the TE task is based on the restored files

functions/src/Spreadsheet.ts
https://trello.com/c/WLQULktf/356-te-import-issue-when-unwanted-parts-is-empty
=> TE import issue when Unwanted Parts is empty

database.rules.bolt, frontend/src/views/TE/Task.vue
https://trello.com/c/IJ1DP4qO/366-show-resolution-controls-only-when-the-status-is-wip
=> Allow resolution only when the status is WIP

database.rules.bolt, functions/src/modules/Email.functions.ts
https://trello.com/c/SsDRDQVp/370-resend-failed-emails
=> Retry failed emails

functions/src/AbstractRepository.ts, functions/src/Allotment.ts, functions/src/AllotmentRow.ts, functions/src/AllotmentValidator.ts, functions/src/ReportingAllotmentRow.ts, functions/src/ReportingTask.ts, functions/src/RequireOnly.ts, functions/src/SoundQualityReporting/SQR.functions.ts, functions/src/SoundQualityReporting/SQRWorkflow.ts, functions/src/SoundQualityReporting/TasksRepository.ts, functions/src/TrackEditing/TE.functions.ts, functions/src/TrackEditing/TasksRepository.ts, functions/src/TrackEditing/TrackEditingAllotmentRow.ts, functions/src/TrackEditing/TrackEditingTask.ts
https://trello.com/c/Z6pdtDpS/373-sqr-status-not-getting-updated-from-the-spreadsheet
=> SQR allotments sync

functions/email.js, functions/emails/mixins.pug
https://trello.com/c/lbKLiUlh/225-the-date-given-and-days-passed-are-missing-in-sqr-submission-email
=> Fix missing date given and days passed in SQR submission email

functions/emails/mixins.pug
https://trello.com/c/bAoO67w7/390-show-full-date-with-slashes-in-the-sqr-current-set-in-emails
=> Show full date with slashes in the SQR current set in emails

functions/src/Allotment.ts, functions/src/SoundQualityReporting/SQRWorkflow.ts, functions/src/SoundQualityReporting/TasksRepository.ts
https://trello.com/c/K4DLh7Qb/389-keep-only-given-and-wip-in-the-sqr-current-set-in-emails
=> Keep only Given and WIP in the SQR current set in emails

frontend/src/views/SQR/Form.vue
https://trello.com/c/auP6dpK2/391-disable-sqr-submission-button-during-submission
=> Disable SQR submission button during submission

frontend/src/components/AssigneeSelector.vue
https://trello.com/c/X7QvuIZw/395-not-able-to-see-language-preferred-on-sqr-allotment-form
=> Always show hint for assignee selector

functions/src/StorageManager.test.ts, functions/src/StorageManager.ts
https://trello.com/c/FdFrunrp/401-se-uploads-are-copied-to-the-destination-bucket-with-incorrect-names
=> Tighten SE uploads regex

functions/src/StorageManager.ts, functions/src/TrackEditing/TasksRepository.ts, functions/src/modules/Files.functions.ts
https://trello.com/c/vlTuT8ou/419-pick-the-most-recent-file-via-magic-download-link
=> Pick the most recent file via magic download link

functions/src/StorageManager.ts
https://trello.com/c/XBgWSzwM/423-incorrect-most-recent-file-in-filesdownload-magic-link
=> Fix getting most recent file in Files.download magic link

functions/src/modules/Files.functions.ts
https://trello.com/c/bY2SY6Ec/424-add-sed-suffix-to-the-downloaded-file-name
=> Add SEd suffix to the downloaded file name

README.md, functions/package-lock.json, functions/package.json, functions/src/FidelityCheck/FC.functions.ts, functions/src/FidelityCheck/FidelityCheckRecord.ts, functions/src/FidelityCheck/FidelityCheckRow.ts, functions/src/FileVersion.ts, functions/src/Spreadsheet.ts, functions/src/StorageFileReference.ts, functions/src/flatten.test.ts
https://trello.com/c/WniBmmos/427-fidelity-check-validation
=> Fidelity check validation

cli/src/commands/digi/prepare.ts
https://trello.com/c/GXDnTO01/428-convert-digi-files-to-256k-bitrate
https://trello.com/c/Dq2b6qYi/429-duration-difference-up-to-1-second-should-be-ignored-in-digi-processing
https://trello.com/c/hbzmVSJJ/430-lower-priority-of-srila-bv-narayan-maharaja-mp3-folder
https://trello.com/c/x3COPQV2/431-digi-prepare-start-converting-after-processing-all-files-save-to-spreadsheet-afterwards
=> DIGI processing adjustments

functions/src/FidelityCheck/FC.functions.ts, functions/src/FidelityCheck/FidelityCheckRecord.ts, functions/src/FidelityCheck/FidelityCheckRow.ts
https://trello.com/c/ICObwLNI/433-fidelity-check-validation-adjustments
=> Fidelity Check validation adjustments

functions/src/DateTimeConverter.test.ts, functions/src/DateTimeConverter.ts, functions/src/FidelityCheck/ContentDetails.ts, functions/src/FidelityCheck/FC.functions.ts, functions/src/FidelityCheck/FidelityCheckRecord.ts, functions/src/FidelityCheck/FidelityCheckRow.ts, functions/src/FidelityCheck/FidelityCheckValidator.ts, functions/src/StorageManager.ts, functions/src/validation/IValidationRule.ts, functions/src/validation/ValidationRule.ts, functions/src/validation/Validator.ts
https://trello.com/c/2DGUfgUn/436-additional-fc-validation
=> Additional FC validation

functions/src/FidelityCheck/FC.functions.ts, functions/src/FidelityCheck/FidelityCheckRow.ts, functions/src/FidelityCheck/FidelityCheckValidator.ts
https://trello.com/c/5N8Vuz63/441-normalize-data-from-spreadsheet-before-processing
=> Normalize data from spreadsheet before processing

functions/src/FidelityCheck/FC.functions.ts, functions/src/FidelityCheck/FinalEntry.ts, functions/src/FidelityCheck/FinalRecord.ts
https://trello.com/c/m9k7ESf3/432-export-final-records-into-archive-database
=> Export final records for Archive

functions/src/FidelityCheck/FC.functions.ts, functions/src/FidelityCheck/FidelityCheckRecord.ts, functions/src/FidelityCheck/FidelityCheckValidator.ts
https://trello.com/c/iljpaGS5/445-ensure-ability-to-unpublish-a-file
=> Ensure ability to unpublish a file

functions/src/TrackEditing/TE.functions.ts, storage.uploads.rules
https://trello.com/c/A3tHHwF4/447-allow-te-checkers-to-upload-files
=> Allow TE checkers to upload files

database.rules.bolt, frontend/src/views/TE/Task.vue, functions/email.js, functions/emails/track-editing/upload/html.pug, functions/emails/track-editing/upload/subject.pug, functions/src/FileVersion.ts, functions/src/TrackEditing/TE.functions.ts, functions/src/TrackEditing/TasksRepository.ts, functions/src/TrackEditing/TrackEditingAllotmentRow.ts
https://trello.com/c/LyOiKo1h/399-save-author-of-the-te-version
=> Store author of the TE version

frontend/src/store/modules/user.ts
https://trello.com/c/A3tHHwF4/447-allow-te-checkers-to-upload-files
=> Allow TE checkers to see Upload page

database.rules.bolt
https://trello.com/c/EIOtSfRS/451-case-insensitive-te-access-rules
=> Case-insensitive TE access rules

functions/src/DateTimeConverter.test.ts, functions/src/DateTimeConverter.ts
=> Allow durations up to 6 hours

functions/package-lock.json, functions/package.json, functions/src/StorageManager.ts, functions/src/modification-time.test.ts, functions/src/modification-time.ts, functions/src/modules/Files.functions.ts
Use `File` type from a transient dependency.
=> Remove direct dependency `@google-cloud/storage`

.github/workflows/ci.yml, .github/workflows/deployment.yml
This only increases the post processing time
but does not improve performance because mostly cache is missing.
=> Disable npm caching in CI

functions/src/AbstractRepository.ts, functions/src/SoundQualityReporting/TasksRepository.ts, functions/src/TrackEditing/TasksRepository.ts
A fix to a bug introduced in 56057db35a8e5015a874e0bd250e8b3f3991e9ba.
=> Fix `syncAllotments`

functions/src/AbstractRepository.ts, functions/src/FidelityCheck/FC.functions.ts, functions/src/SoundQualityReporting/SQRWorkflow.ts, functions/src/SoundQualityReporting/TasksRepository.ts, functions/src/TrackEditing/TasksRepository.ts, functions/src/metadata-database.ts, functions/src/modules/Files.functions.ts, functions/src/publication/Final.functions.ts, functions/src/schema/migrations/2024-02-07-FC-durations.ts
This is needed to avoid constant error messages in the emulator console: `@firebase/database: FIREBASE WARNING`
=> Access the Firebase Admin app only from a function
